import MainLayout from "@/components/common/Layouts/MainLayout/MainLayout";
import Login from "@/components/pages/login/Login";
import { useAppSelector } from "@/hooks";
import Head from "next/head";

export default function LoginPage() {
  const { brandName } = useAppSelector(state => state.app);
  const { login } = useAppSelector(state => state.auth)
  return (
    <>
      <Head>
        <title>Giriş Yap | {brandName}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout login={login}>
        <Login />
      </MainLayout>
    </>
  )

}