import MainLayout from '@/components/common/Layouts/MainLayout/MainLayout';
import Head from 'next/head'
import React from "react";
import Home from '@/components/pages/home/Home';
import { GetServerSideProps } from 'next/types';
import { getAllEntries, getCaptions } from '@/services/api';
import { useAppDispatch, useAppSelector } from '@/hooks';
import useUpdateEffect from '@/hooks/useUpdateEffect';
import { IndexPageProps } from '@/types/pages';
import { clearHomeEntries, setHomeEntries, setHomePagination } from '@/features/entry/entry';
import { setLeftSideBar } from '@/features/caption/caption';

export default function Index(props: IndexPageProps) {
  const dispatch = useAppDispatch();
  const { brandName } = useAppSelector(state => state.app);


  useUpdateEffect(() => {
    dispatch(clearHomeEntries());
    dispatch(setLeftSideBar(props.captions));
    dispatch(setHomeEntries(props.entries.data));
    dispatch(setHomePagination({ page: props.entries.pagination.current_page, total: props.entries.pagination.total_pages }))
  }, [dispatch])

  return (
    <>
      <Head>
        <title>Anasayfa | {brandName} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Home />
      </MainLayout>
    </>
  )
}
export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await getCaptions({ page: 1 })
  const entries = await getAllEntries({ page: 1 });
  return {
    props: {
      captions: res.payload.data,
      entries: entries.payload
    },
  }
}