import MainLayout from '@/components/common/Layouts/MainLayout/MainLayout';
import Head from 'next/head'
import React from "react";
import Home from '@/components/pages/home/Home';
import { GetServerSideProps } from 'next/types';
import { getAllEntries, getCaptions, getTopics } from '@/services/api';
import { useAppDispatch, useAppSelector } from '@/hooks';
import useUpdateEffect from '@/hooks/useUpdateEffect';
import { IndexPageProps } from '@/types/pages';
import { clearHomeEntries, setHomeEntries, setHomePagination } from '@/features/entry/entry';
import { setLeftSideBar } from '@/features/caption/caption';
import { setTopicData } from '@/features/topic/topic';

export default function Index(props: IndexPageProps) {
  const dispatch = useAppDispatch();
  const { brandName } = useAppSelector(state => state.app);
  const { active_topic } = useAppSelector(state => state.topic)

  useUpdateEffect(() => {
    dispatch(clearHomeEntries());
    if(!active_topic){
      dispatch(setLeftSideBar(props.captions.payload.data));
    }
    dispatch(setHomeEntries(props.entries.payload.data));
    dispatch(setHomePagination({ page: props.entries.payload.pagination.current_page, total: props.entries.payload.pagination.total_pages }))
    dispatch(setTopicData(props.topics.payload));
  }, [dispatch])

  return (
    <>
      <Head>
        <title>Anasayfa | {brandName} </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Home />
      </MainLayout>
    </>
  )
}
export const getServerSideProps: GetServerSideProps = async (context) => {
  const captions = await getCaptions({ page: 1 })
  const entries = await getAllEntries({ page: 1 });
  const topics = await getTopics();
  return {
    props: {
      captions: captions,
      entries: entries,
      topics: topics
    },
  }
}