import MainLayout from '@/components/common/Layouts/MainLayout/MainLayout';
import Head from 'next/head'
import React from "react";
import Home from '@/components/pages/home/Home';
import { GetServerSideProps } from 'next/types';
import { getAllEntries, getCaptions } from '@/services/api';
import { useAppDispatch } from '@/hooks';
import useUpdateEffect from '@/hooks/useUpdateEffect';
import { setEntries, setEntryPaginate, setLeftSideBar } from '@/features/app/app';
import { IndexPageProps } from '@/types/pages';

export default function Index(props: IndexPageProps) {
  const dispatch = useAppDispatch();

  useUpdateEffect(() => {
    dispatch(setLeftSideBar(props.captions));
    dispatch(setEntries(props.entries.data));
    dispatch(setEntryPaginate({ page: props.entries.pagination.current_page, total: props.entries.pagination.total, perPage: props.entries.pagination.per_page }))
  }, [dispatch])

  return (
    <>
      <Head>
        <title>Sözlük </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <Home />
      </MainLayout>
    </>
  )
}
export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await getCaptions({ page: 1 })
  const entries = await getAllEntries({ page: 1 });
  return {
    props: {
      captions: res.payload.data,
      entries: entries.payload
    },
  }
}