import MainLayout from "@/components/common/Layouts/MainLayout/MainLayout";
import Register from "@/components/pages/register/Register";
import { useAppSelector } from "@/hooks";
import Head from "next/head";

export default function RegisterPage() {
    const { brandName } = useAppSelector(state => state.app);
    const { login } = useAppSelector(state => state.auth)

    return (
        <>
            <Head>
                <title>Kayıt Ol | {brandName}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <MainLayout showLoading={false} login={login}>
                <Register  />
            </MainLayout>
        </>
    )

}